### ISSUE TITLE
Design Lab 1.0.3, papilio-prog and libftdi on Fedora 21

### ISSUE THREAD

**Issue by nowatson** [GadgetFactory/DesignLab#15]
On Fedora 21 I had to install both the 32 and 64 bit versions of the libftdi as the Design Lab 1.0.3 64 bit download contains and uses both the 32bit and 64 bit versions of papilio-prog

Can you only include 64 bit the version of papilio-prog in the 64 bit download?

Furthermore, Fedora 21 uses a more recent version of libftdi (v1.2), and the library is actually called libftdi1.

/usr/lib/libftdi1.so.2
/usr/lib64/libftdi1.so.2

I can fix this by creating 2 symbolic links as shown below
/usr/lib/libftdi.so.1 -> libftdi1.so.2
/usr/lib64/libftdi.so.1 -> libftdi1.so.2

Can you create these symbolic links in your ftdi_user.sh script if required?

On a related note, can you only include and reference a single papilio-prog in the download zip? I count it included 5 different times

./hardware/tools/papilio/papilio-prog
./hardware/tools/papilio/lin64/papilio-prog
./hardware/tools/papilio/papilio_loader/papilio-prog
./hardware/tools/papilio/lin32/papilio-prog
./tools/Papilio_Loader/programmer/linux32/papilio-prog

**Comment by jackgassett** [comment]
The build.xml file has been fixed so the linux64 version of the binaries are copied over correctly now. In addition the different instances of papilio-prog have been cleaned up.

ftdi_user.sh has been renamed to setup-ubuntu.sh. If you have changes for Fedora that you would like to see included please create a setup-fedora.sh file and submit to me for inclusion.

Jack.
