### ISSUE TITLE
Designlab 1.0.6 load circuit

### ISSUE THREAD

**Issue by pilif-pilif** [GadgetFactory/DesignLab#30]
Hello,
when I hit the load button I get:
*C:\DesignLab-1.0.6\hardware\tools\papilio\papilio_loader\Papilio_Programmer.bat* *\..\Papilio_Programmer.sh: line 4: $'\r': command not found*
*C:\DesignLab-1.0.6\hardware\tools\papilio\papilio_loader\Papilio_Programmer.bat\..\Papilio_Programmer.sh: line 5: set: - : invalid option*
*set: usage: set [--abefhkmnptuvxBCHP] [-o option-name] [arg ...]*
*C:\DesignLab-1.0.6\hardware\tools\papilio\papilio_loader\Papilio_Programmer.bat**\..\Papilio_Programmer.sh: line 6: $'\r': command not found*
*C:\DesignLab-1.0.6\hardware\tools\papilio\papilio_loader\Papilio_Programmer.bat* *\..\Papilio_Programmer.sh: line 8: $'\r': command not found*
*C:\DesignLab-1.0.6\hardware\tools\papilio\papilio_loader\Papilio_Programmer.bat* *\..\Papilio_Programmer.sh: line 14: $'\r': command not found*
*C:\DesignLab-1.0.6\hardware\tools\papilio\papilio_loader\Papilio_Programmer.bat* *\..\Papilio_Programmer.sh: line 16: $'\r': command not found*
*C:\DesignLab-1.0.6\hardware\tools\papilio\papilio_loader\Papilio_Programmer.bat* *\..\Papilio_Programmer.sh: line 17: syntax error near unexpected token `$'in\r''*
*C:\DesignLab-1.0.6\hardware\tools\papilio\papilio_loader\Papilio_Programmer.bat* *\..\Papilio_Programmer.sh: line 17: `case "$return_value" in *

I'm on Windows 7 32bit

**Comment by jackgassett** [comment]
This was caused by git's auto line ending stuff. I released a new version 1.0.6b to correct this issue.
