### ISSUE TITLE
update readme

### ISSUE THREAD

**Issue by goretkin** [GadgetFactory/DesignLab#33]
It looks the the actual readme lives in `readme.txt`. If you rename it to `README.md` (deleting the existing one), then it will show on the github project page.

Are there build instructions for the DesignLab IDE?

**Comment by jackgassett** [comment]
Thank you for that tip! I just renamed the readme.md to readme.md.orig so that the DesignLab readme.txt becomes the default.

This build instructions are the same as for the Arduino IDE.
